[workspace]
members = [
    "Unilyric",
    "lyrics_helper_core",
    "lyrics_helper_rs",
    "ttml_processor",
]

resolver = "3"

[patch.crates-io]
lyrics_helper_core = { path = "lyrics_helper_core" }
ttml_processor = { path = "ttml_processor" }
