# metadata_stripper 的默认关键词和正则表达式。

keywords = [
    "作曲",
    "作词",
    "编曲",
    "演唱",
    "歌手",
    "歌名",
    "专辑",
    "发行",
    "出品",
    "监制",
    "录音",
    "混音",
    "母带",
    "吉他",
    "贝斯",
    "鼓",
    "键盘",
    "弦乐",
    "和声",
    "版权",
    "制作人",
    "原唱",
    "翻唱",
    "词",
    "曲",
    "发行人",
    "发行公司",
    "宣推",
    "录音制作",
    "制作发行",
    "制作团队",
    "音乐制作",
    "录音师",
    "混音工程师",
    "混音师",
    "母带工程师",
    "母带处理工程师",
    "制作统筹",
    "艺术指导",
    "出品团队",
    "发行方",
    "和声编写",
    "封面设计",
    "策划",
    "营销推广",
    "总策划",
    "特别鸣谢",
    "出品人",
    "出品公司",
    "联合出品",
    "词曲提供",
    "制作公司",
    "推广策划",
    "乐器演奏",
    "钢琴/合成器演奏",
    "钢琴演奏",
    "合成器演奏",
    "弦乐编写",
    "弦乐监制",
    "第一小提琴",
    "第二小提琴",
    "中提琴",
    "大提琴",
    "弦乐录音师",
    "弦乐录音室",
    "和声演唱",
    "录/混音",
    "制作助理",
    "和音",
    "乐队统筹",
    "维伴音乐",
    "灯光设计",
    "配唱制作人",
    "文案",
    "设计",
    "策划统筹",
    "企划宣传",
    "企划营销",
    "录音室",
    "混音室",
    "母带后期制作人",
    "母带后期处理工程师",
    "母带后期处理录音室",
    "鸣谢",
    "工作室",
    "特别企划",
    "音频编辑",
    "词曲协力",
    "制作公司/OP",
    "企划",
    "宣传",
    "统筹",
    "推广",
    "宣传/推广",
    "出品/发行",
    "出品/发行方",
    "封面",
    "总企划",
    "混缩",
    "联合策划",
    "联合推广",
    "题记",
    "项目统筹",
    "营销推广/出品/发行",
    "出品/发行公司",
    "音乐制作发行",
    "本歌曲商用授权，前往小程序",
    "特别鸣谢/艺人支持",
    "出品、发行",
    "推广宣传",
    "OP、SP",
    "和声/和声设计",
    "合声",
    "合声编写",
    "OP",
    "SP",
    "Lyrics by",
    "Composed by",
    "Produced by",
    "Published by",
    "Vocals by",
    "Background Vocals by",
    "Additional Vocal by",
    "Mixing Engineer",
    "Mastered by",
    "Executive Producer",
    "Vocal Engineer",
    "Vocals Produced by",
    "Recorded at",
    "Repertoire Owner",
    "Co-Producer",
    "Mastering Engineer",
    "Written by",
    "Lyrics",
    "Composer",
    "Arranged By",
    "Record Producer",
    "Guitar",
    "Music Production",
    "Recording Engineer",
    "Backing Vocal",
    "Art Director",
    "Chief Producer",
    "Production Team",
    "Publisher",
    "Lyricist",
    "Arranger",
    "Producer",
    "Backing Vocals",
    "Backing Vocals Design",
    "Cover Design",
    "Planner",
    "Marketing Promotion",
    "Chref Planner",
    "Acknowledgement",
    "Production Company",
    "Jointly Produced by",
    "Co-production",
    "Presenter",
    "Presented by",
    "Co-produced by",
    "Lyrics and Composition Provided by",
    "Music and Lyrics Provided by",
    "Lyrics & Composition Provided by",
    "Words and Music by",
    "Distribution",
    "Release",
    "Distributed by",
    "Released by",
    "Produce Company",
    "Promotion Planning",
    "Marketing Strategy",
    "Promotion Strategy",
    "Strings",
    "First Violin",
    "Second Violin",
    "Viola",
    "Cello",
    "Vocal Producer",
    "Supervised production",
    "Copywriting",
    "Design",
    "Planner and coordinator",
    "Propaganda",
    "Arrangement",
    "Guitars",
    "Bass",
    "Drums",
    "Backing Vocal Arrangement",
    "Strings Arrangement",
    "Recording Studio",
    "OP/发行",
    "混音/母带工程师",
    "OP/SP",
    "词Lyrics",
    "曲Composer",
    "编曲Arranged By",
    "制作人Record Producer",
    "吉他Guitar",
    "音乐制作Music Production",
    "录音师Recording Engineer",
    "混音工程师Mixing Engineer",
    "母带工程师Mastering Engineer",
    "和声Backing Vocal",
    "制作统筹Executive Producer",
    "艺术指导Art Director",
    "监制Chief Producer",
    "出品团队Production Team",
    "发行方Publisher",
    "词Lyricist",
    "编曲Arranger",
    "制作人Producer",
    "和声Backing Vocals",
    "和声编写Backing Vocals Design",
    "混音Mixing Engineer",
    "封面设计Cover Design",
    "策划Planner",
    "营销推广Marketing Promotion",
    "总策划Chref Planner",
    "特别鸣谢Acknowledgement",
    "出品人Chief Producer",
    "出品公司Production Company",
    "联合出品Co-produced by",
    "联合出品Jointly Produced by",
    "联合出品Co-production",
    "出品方Presenter",
    "出品方Presented by",
    "词曲提供Lyrics and Composition Provided by",
    "词曲提供Music and Lyrics Provided by",
    "词曲提供Lyrics & Composition Provided by",
    "词曲提供Words and Music by",
    "发行Distribution",
    "发行Release",
    "发行Distributed by",
    "发行Released by",
    "制作公司Produce Company",
    "推广策划Promotion Planning",
    "推广策划Marketing Strategy",
    "推广策划Promotion Strategy",
    "弦乐 Strings",
    "第一小提琴 First Violin",
    "第二小提琴 Second Violin",
    "中提琴 Viola",
    "大提琴 Cello",
    "配唱制作人Vocal Producer",
    "监制Supervised production",
    "文案Copywriting",
    "设计Design",
    "策划统筹Planner and coordinator",
    "企划宣传Propaganda",
    "编曲Arrangement",
    "吉他Guitars",
    "贝斯Bass",
    "鼓Drums",
    "和声编写Backing Vocal Arrangement",
    "弦乐编写Strings Arrangement",
    "录音室Recording Studio",
    "混音室Mixing Studio",
    "母带后期制作人Mastering Producer",
    "母带后期处理工程师Mastering Engineer",
    "母带后期处理录音室Mastering Studio",
    "制作人Music Producer",
    "统筹Planning",
    "营销推广Marketing",
    "出品人Producer",
    "企划Planning",
    "监制Executive Director",
    "统筹Coordinator",
    "出品人Publisher",
    "出品Present by",
    "词 Lyricist",
    "曲 Composer",
    "编曲 Arranger",
    "制作人 Producer",
    "配唱制作人 Vocals Producer",
    "吉他 Guitar",
    "和声 Backing Vocals",
    "混音 Mixing Engineer",
    "录音 Recording Engineer",
    "录音室 Recording Studio",
    "封面设计 Cover Design",
    "策划 Planner",
    "推广营销 Marketing Promotion",
    "总策划 Chief Planner",
    "出品人 Publisher",
    "制作公司 Production",
    "项目统筹 Project Coordinator",
    "推广统筹 Promotion Coordinator",
    "监制 Deputy Executive Producer",
    "总监制 Chief Executive Producer",
    "企划制作A&R Planning",
    "音乐项目总监Project Executive",
    "联合出品Published",
    "出品人Presenter",
    "封面插画Cover illustration",
    "和音 Bvox",
    "混音 Mixed by",
    "母带 Mastered by",
]

regex_patterns = [
    "(?:【.*?未经.*?】|\\(.*?未经.*?\\)|「.*?未经.*?」|（.*?未经.*?）|『.*?未经.*?』)",
    "(?:【.*?音乐人.*?】|\\(.*?音乐人.*?\\)|「.*?音乐人.*?」|（.*?音乐人.*?）|『.*?音乐人.*?』)",
    ".*?未经.*?许可.*?不得.*?使用.*?",
    ".*?未经.*?许可.*?不得.*?方式.*?",
    "未经著作权人书面许可，\\s*不得以任何方式\\s*[(\\u{FF08}]包括.*?等[)\\u{FF09}]\\s*使用",
]
